### ISSUE TITLE
[Feature] CPU Pinning

### ISSUE THREAD

**Issue by lukepolo** [5stackgg/api#49]
Modify `/var/lib/kubelet/config.yaml` 

```
cpuManagerPolicy: static
cpuManagerReconcilePeriod: 5s
reservedSystemCPUs: "0,1"  # CPUs reserved for system/kubelet
```

Restart kubelet

```
sudo systemctl restart kubelet
```

During Pod creation setup limits

```
    resources:
      requests:
        cpu: "1"
      limits:
        cpu: "1"
```
